apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels: {app: consumer}
  template:
    metadata:
      labels: {app: consumer}
    spec:
      containers:
        - name: consumer
          image: stock-consumer:latest
          imagePullPolicy: Never
          env:
            - {name: KAFKA_BOOTSTRAP_SERVERS, value: "kafka:9092"}
            - {name: POSTGRES_HOST, value: "postgres"}
            - {name: POSTGRES_PORT, value: "5432"}
            - {name: REDIS_HOST, value: "redis"}
            - {name: REDIS_PORT, value: "6379"}
          envFrom:
            - secretRef: {name: app-secrets}